add sequence classification with ernie finetuned in dygraph
PaddlePaddle/PaddleFormers pull request #1045
Opened 2020-11-25 12:36 UTC by Steffy-zxf

1. ernie module depended on paddlenlp/transformers
2. add chnsenticorp,BertTokenizer
3. fix some bugs in trainer

2020-11-26 17:33 UTC, ZeyuChen requested changes
把paddlenlp大量的代码存放到hub.text中

2020-11-26 17:33 UTC, ZeyuChen commented on modules/text/language_model/bert_cased_L_12_H_768_A_12/module.py
> +class BertForSequenceClassification(BertPretrainedModel):
我理解应该把这些类放在hub核心库中，例如放一个hub.text的包，然后到时paddlenlp发布了，就直接将hub.text里面的api替换为paddlenlp的api就好了。
然后在module这里以hub API的方式去调用，这样可以弱化modules里面的依赖，轻量化一些

2020-11-26 17:33 UTC, ZeyuChen commented on modules/text/language_model/bert_cased_L_12_H_768_A_12/module.py
> +class BertPretrainedModel(PretrainedModel):
我理解应该把这些类放在hub核心库中，例如放一个hub.text的包，然后到时paddlenlp发布了，就直接将hub.text里面的api替换为paddlenlp的api就好了。
然后在module这里以hub API的方式去调用，这样可以弱化modules里面的依赖，轻量化一些

2020-11-26 17:33 UTC, ZeyuChen commented on modules/text/language_model/bert_cased_L_12_H_768_A_12/module.py
> +from paddlehub import BertTokenizer
`from paddlehub.text import BertTokenizer`
然后等paddlenlp出来，把hub.text里面的api都替换成paddlenlp.xxx.BertTokenizer就好

2020-11-27 02:57 UTC, Steffy-zxf commented on modules/text/language_model/bert_cased_L_12_H_768_A_12/module.py
> +class BertForSequenceClassification(BertPretrainedModel):
已修改

2020-11-27 02:58 UTC, Steffy-zxf commented on modules/text/language_model/bert_cased_L_12_H_768_A_12/module.py
> +class BertPretrainedModel(PretrainedModel):
目前是 放在`paddlehub.module`下

2020-11-27 02:58 UTC, Steffy-zxf commented on modules/text/language_model/bert_cased_L_12_H_768_A_12/module.py
> +from paddlehub import BertTokenizer
ok

2020-11-27 15:42 UTC, ZeyuChen approved these changes
LGTM

2020-11-30 03:05 UTC, nepeplwu commented on paddlehub/text/bert_tokenizer.py
> +if __name__ == "__main__":
main建议去掉，尤其不要出现这种和本地路径相关的代码

2020-11-30 03:05 UTC, nepeplwu commented on paddlehub/datasets/chnsenticorp.py
> +if __name__ == "__main__":
main建议去掉

2020-11-30 03:05 UTC, nepeplwu commented on modules/text/language_model/ernie_v2_eng_large/module.py
> +    author_email="paddle-dev@baidu.com",
这个邮箱应该已经废弃，建议去掉

2020-11-30 03:49 UTC, Steffy-zxf commented on paddlehub/text/bert_tokenizer.py
> +if __name__ == "__main__":
已去除

2020-11-30 03:49 UTC, Steffy-zxf commented on paddlehub/datasets/chnsenticorp.py
> +if __name__ == "__main__":
已去除

2020-11-30 03:49 UTC, Steffy-zxf commented on modules/text/language_model/ernie_v2_eng_large/module.py
> +    author_email="paddle-dev@baidu.com",
已去除

2020-11-30 11:20 UTC, merged