Add token-cls task and sequence labeling demo
PaddlePaddle/PaddleFormers pull request #1121
Opened 2020-12-16 09:33 UTC by KPatr1ck

@nepeplwu  @Steffy-zxf 

- Add MSRA dataset
- Add token_cls task and multi-classes case in ernie_tiny 
- Add sequence_labeling demo on MSRA

2020-12-16 09:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleHub?pullRequest=1121) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleHub?pullRequest=1121) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleHub?pullRequest=1121) it.</sub>

2020-12-17 02:36 UTC, Steffy-zxf requested changes
同时，
1. 注意下paddlehub/module/下 关于transformer类模型的modeling 文件的删除。
2. 对于nlp支持finetune的module需要抽象出一个基类，公用`training_step` 和 `validation_step`的方法

2020-12-17 02:36 UTC, Steffy-zxf commented on demo/sequence_labeling/train.py
> +        max_seq_len=50,
`max_seq_len`设置有点小。可以看看MSRA_NER数据集文本平均长度是多少

2020-12-17 02:36 UTC, Steffy-zxf commented on demo/sequence_labeling/train.py
> +    trainer = hub.Trainer(model, optimizer, checkpoint_dir='token_cls_save_dir', use_gpu=False)
建议默认开启gpu训练

2020-12-17 02:36 UTC, Steffy-zxf commented on demo/sequence_labeling/train.py
> +    trainer.train(train_dataset, epochs=1, batch_size=16, eval_dataset=dev_dataset, save_interval=1)
`epoch`，`batch`设置也有点小。建议参考1.8分支下对应demo的config设置

2020-12-17 02:36 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +            num_classes=2,
建议这里可以再增加一个**kwargs，支持用户透传参数

2020-12-17 02:36 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +            warn(
使用`logger.warning(***)`，参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0.0-beta/paddlehub/module/module.py#L270

2020-12-17 02:36 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +            self.model = ErnieForSequenceClassification.from_pretrained(pretrained_model_name_or_path='ernie_tiny', num_classes=self.num_classes)
`self.model = ErnieForSequenceClassification.from_pretrained(pretrained_model_name_or_path='ernie-tiny', num_classes=self.num_classes) `

paddlenlp已经将 ernie_tiny 重命名为 ernie-tiny

2020-12-17 02:36 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +            self.metric = paddle.metric.Accuracy(name='acc_accumulation')
这里去掉metric指定name吧。`paddle.metric.Accuracy()`

2020-12-17 02:36 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +            self.model = ErnieForTokenClassification.from_pretrained(pretrained_model_name_or_path='ernie_tiny', num_classes=self.num_classes)
同上

2020-12-17 02:36 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
>              self.metric = paddle.metric.Accuracy(name='acc_accumulation')
同上

2020-12-17 02:36 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
>              self.model = ErnieModel.from_pretrained(pretrained_model_name_or_path='ernie_tiny')
同上

2020-12-17 02:36 UTC, Steffy-zxf commented on paddlehub/datasets/base_nlp_dataset.py
> +class SeqLabelingDataset(BaseNLPDataset, fluid.io.Dataset):
去掉fluid，使用paddle.io.DataSet
其他代码如果有出现fluid，同样也去掉

加上相应的注释

2020-12-17 03:54 UTC, nepeplwu commented on demo/sequence_labeling/README.md
> +本示例将展示如何使用PaddleHub Transformer模型（如 ERNIE、BERT、RoBERTa等模型）module 以动态图方式fine-tune并完成预测任务。
module建议首字母大写`Module`

2020-12-17 03:54 UTC, nepeplwu commented on demo/sequence_labeling/README.md
> +paddlenlp >= 2.0.0
依赖paddlenlp的2.0.0beta版本还是正式版本？

2020-12-17 03:54 UTC, nepeplwu commented on paddlehub/datasets/base_nlp_dataset.py
> +        with tqdm(total=len(examples)) as process_bar:
如果数据处理耗时不久的话，建议不加入tqdm的依赖

2020-12-17 03:54 UTC, nepeplwu commented on paddlehub/datasets/base_nlp_dataset.py
> +    def _reseg_token_label(self, tokens, labels=None):
token，labels缺少annotation。其他接口请再检查一遍

2020-12-17 03:54 UTC, nepeplwu commented on paddlehub/datasets/msra_ner.py
> +if __name__ == "__main__":
main相关的代码建议去除

2020-12-17 03:54 UTC, nepeplwu commented on demo/sequence_labeling/README.md
> +paddlenlp >= 2.0.0
另外，requirements里面需要补充上paddlenlp的依赖

2020-12-17 03:54 UTC, nepeplwu commented on modules/text/language_model/ernie_tiny/module.py
> +            warn(
建议直接用hub内置的logger.warning来提示警告

2020-12-17 10:55 UTC, KPatr1ck commented on demo/sequence_labeling/train.py
> +        max_seq_len=50,
根据1.8版本的教程，改成了128

2020-12-17 10:59 UTC, KPatr1ck commented on demo/sequence_labeling/README.md
> +paddlenlp >= 2.0.0
已改为 2.0.0a4，`requirements.txt`中也添加了

2020-12-18 02:22 UTC, Steffy-zxf reviewed
README 可以参考 这个教程 https://aistudio.baidu.com/aistudio/projectdetail/1283423， 把一些图文说明可以用上。

2020-12-18 02:22 UTC, Steffy-zxf commented on requirements.txt
> +paddlenlp >= 2.0.0a4
paddlenlp >= 2.0.0b

2020-12-18 02:28 UTC, Steffy-zxf reviewed
文本分类 和 序列标注readme 参考教程 https://aistudio.baidu.com/aistudio/projectdetail/1294333
把相应图文说明加上。

2020-12-18 02:28 UTC, Steffy-zxf commented on demo/sequence_labeling/README.md
> +* `name`：模型名称，可以选择`ernie`，`ernie-tiny`，`bert_chinese_L-12_H-768_A-12`，`chinese-roberta-wwm-ext`，`chinese-roberta-wwm-ext-large`等。
bert系列 我记得 改了名称

2020-12-18 02:28 UTC, Steffy-zxf commented on demo/sequence_labeling/README.md
> +paddlenlp >= 2.0.0a4
paddlenlp 依赖可以去掉 因为在requirements.txt里有

2020-12-18 02:39 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +            logger.warning(
warning可以加上 Deprecated 字眼，强调下。

2020-12-18 17:40 UTC, KPatr1ck commented on demo/sequence_labeling/README.md
> +* `name`：模型名称，可以选择`ernie`，`ernie-tiny`，`bert_chinese_L-12_H-768_A-12`，`chinese-roberta-wwm-ext`，`chinese-roberta-wwm-ext-large`等。
已改，和module名字同步

2020-12-22 03:15 UTC, Steffy-zxf approved these changes
LGTM

2020-12-22 03:16 UTC, merged