Update transformer modules
PaddlePaddle/PaddleFormers pull request #1147
Opened 2020-12-25 06:17 UTC by KPatr1ck

2020-12-27 05:39 UTC, Steffy-zxf requested changes
以上意见，其他类似地方注意修改

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-cased/module.py
>  from paddlehub import BertTokenizer
可以尝试从paddlenlp调用相应的tokenizer

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-cased/module.py
> +                labels = paddle.to_tensor(labels).unsqueeze(-1)
为什么labels 还需要再转换成tensor，labels应该是从dataloader中返回的，已经是tensor了。

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-chinese/README.md
>      data,
texts，同理其他文档注意修改

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-chinese/README.md
>  * `data`： 待预测数据，格式为\[\[sample\_a\_text\_a, sample\_a\_text\_b\], \[sample\_b\_text\_a, sample\_b\_text\_b\],…,\]，其中每个元素都是一个样例，
texts，同理其他文档注意修改

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-cased/module.py
> +                correct = self.metric.compute(token_level_probs, labels)
metric的处理 需要注意 label padding的情况。参考 这里的处理方式：https://github.com/PaddlePaddle/models/blob/release/2.0-beta/PaddleNLP/examples/named_entity_recognition/msra_ner/run_msra_ner.py#L316

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-cased/README.md
>      data,
texts，同理注意其他文档的修改

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-cased/README.md
>      texts,
texts，同理注意其他文档的修改

2020-12-27 05:39 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-cased/module.py
> +            self.metric = paddle.metric.Accuracy()
序列标注任务指标一般使用f1 score

2020-12-27 05:54 UTC, Steffy-zxf commented on modules/text/language_model/bert-base-cased/README.md
> +    ['这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般'],
这是适用于 序列标注任务的 预测数据？为什么 要改变成 预测数据为 list的list ，建议和之前版本参数数据格式保持统一。

2020-12-29 07:24 UTC, KPatr1ck commented on modules/text/language_model/bert-base-cased/module.py
>  from paddlehub import BertTokenizer
目前已在ernie_tiny修改，reivew通过后其他模块同步修改

2020-12-29 07:25 UTC, KPatr1ck commented on modules/text/language_model/bert-base-cased/module.py
> +                labels = paddle.to_tensor(labels).unsqueeze(-1)
已改

2020-12-29 07:26 UTC, KPatr1ck commented on modules/text/language_model/bert-base-cased/module.py
> +                correct = self.metric.compute(token_level_probs, labels)
数据集中针对padding的label特殊处理，并在cross entropy中加入对应的ignore_label

2020-12-29 07:27 UTC, KPatr1ck commented on modules/text/language_model/bert-base-cased/module.py
> +            self.metric = paddle.metric.Accuracy()
与paddlenlp同步，使用paddlenlp.metrics.ChunkEvaluator计算f1 score

2020-12-29 07:28 UTC, KPatr1ck commented on modules/text/language_model/bert-base-cased/README.md
> +    ['这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般'],
这个README.md里的代码片无法运行，查看了demo/text_classification里的示例代码，用的是List[List[str]]，所以才把这里的改了

2020-12-30 03:02 UTC, Steffy-zxf commented on paddlehub/datasets/base_nlp_dataset.py
> +        self.chunk_scheme = chunk_scheme.value
需要检查下 用户传入的 chunk_scheme 是否符合预期。

2020-12-30 06:13 UTC, KPatr1ck commented on paddlehub/datasets/base_nlp_dataset.py
> +        self.chunk_scheme = chunk_scheme.value
已加强制类型校验

2020-12-30 06:31 UTC, KPatr1ck commented on modules/text/language_model/bert-base-chinese/README.md
>      data,
https://github.com/PaddlePaddle/PaddleHub/pull/1137
统一改成data

2020-12-30 06:32 UTC, KPatr1ck commented on modules/text/language_model/bert-base-chinese/README.md
>  * `data`： 待预测数据，格式为\[\[sample\_a\_text\_a, sample\_a\_text\_b\], \[sample\_b\_text\_a, sample\_b\_text\_b\],…,\]，其中每个元素都是一个样例，
https://github.com/PaddlePaddle/PaddleHub/pull/1137
统一改成data

2020-12-30 06:33 UTC, KPatr1ck commented on modules/text/language_model/bert-base-cased/README.md
>      data,
https://github.com/PaddlePaddle/PaddleHub/pull/1137
统一改成data

2020-12-30 06:33 UTC, KPatr1ck commented on modules/text/language_model/bert-base-cased/README.md
>      texts,
https://github.com/PaddlePaddle/PaddleHub/pull/1137
统一改成data

2020-12-30 15:57 UTC, Steffy-zxf approved these changes
LGTM

2020-12-30 15:57 UTC, merged