Add embedding finetune demo
PaddlePaddle/PaddleFormers pull request #1204
Opened 2021-01-20 11:28 UTC by KPatr1ck

2021-01-21 02:53 UTC, Steffy-zxf requested changes
1. word embedding module 需要增加get_vocab_path 方法
2. tokenizer直接使用paddlenlp.JiebaTokenizer
3. 增加使用embedding 预测脚本

2021-01-21 02:53 UTC, Steffy-zxf commented on demo/text_classification/embedding/embedding_classification.py
> +    tokenizer = CustomTokenizer(vocab=vocab, cut_function=jieba.cut)
tokenizer 换成`JiebaTokenizer`，保持和 paddlenlp 一致。直接调用paddlenlp.JiebaTokenizer即可
这里换成 `module.get_vocab_path()`, 保持和Transformer类模型使用统一。

2021-01-21 02:53 UTC, Steffy-zxf commented on paddlehub/text/tokenizer.py
> +    def __call__(self, text):
为什么 要增加call方法

2021-01-21 12:20 UTC, KPatr1ck commented on paddlehub/text/tokenizer.py
> +    def __call__(self, text):
已回退，CustomTokenizer不修改
用paddlenlp的JiebaTokenizer

2021-01-21 12:20 UTC, KPatr1ck commented on demo/text_classification/embedding/embedding_classification.py
> +    tokenizer = CustomTokenizer(vocab=vocab, cut_function=jieba.cut)
tokenizer已换成JiebaTokenizer

2021-01-21 12:44 UTC, Steffy-zxf requested changes

2021-01-21 12:44 UTC, Steffy-zxf commented on paddlehub/datasets/base_nlp_dataset.py
> +            elif isinstance(self.tokenizer, JiebaTokenizer):
序列标注数据集，应该不需要切词。因为数据集已经划分好了的每个token

2021-01-21 12:44 UTC, Steffy-zxf commented on paddlehub/utils/utils.py
> +def normalize_sequence(ids: List[int], max_seq_len: int, vocab: Vocab, return_length: bool = True):
建议拆分成2个函数，一个pad_sequence，一个trunc_sequence。

2021-01-22 11:34 UTC, KPatr1ck commented on demo/text_classification/embedding/embedding_classification.py
> +    tokenizer = CustomTokenizer(vocab=vocab, cut_function=jieba.cut)
tokenizer统一为从model中获取

2021-01-22 11:35 UTC, KPatr1ck commented on paddlehub/datasets/base_nlp_dataset.py
> +            elif isinstance(self.tokenizer, JiebaTokenizer):
针对序列标注数据集，以分隔符中间的token为最小单位转换为词典id

2021-01-22 11:35 UTC, KPatr1ck commented on paddlehub/utils/utils.py
> +def normalize_sequence(ids: List[int], max_seq_len: int, vocab: Vocab, return_length: bool = True):
已拆开成pad_sequence和trunc_sequence。

2021-01-25 02:34 UTC, Steffy-zxf requested changes

2021-01-25 02:34 UTC, Steffy-zxf commented on paddlehub/utils/utils.py
> +    Pad s sequence to max_seq_len
Pads

2021-01-25 02:34 UTC, Steffy-zxf commented on paddlehub/utils/utils.py
> +    '''
Truncates

2021-01-25 02:34 UTC, Steffy-zxf commented on demo/text_classification/embedding/model.py
> +        probs = F.softmax(logits, axis=1)
CrossEntropy里面 会自动加上 softmax。
所以训练时，不需要计算F.softmax，但预测时需要。

2021-01-25 04:58 UTC, KPatr1ck commented on paddlehub/utils/utils.py
> +    Pad s sequence to max_seq_len
已改正

2021-01-25 04:58 UTC, KPatr1ck commented on paddlehub/utils/utils.py
> +    '''
已改正

2021-01-27 02:17 UTC, Steffy-zxf approved these changes
LGTM

2021-01-27 02:17 UTC, merged