Enhancetask
PaddlePaddle/PaddleFormers pull request #122
Opened 2019-08-17 09:34 UTC by kinghuin

1. The predict can judge if the model has been loaded
2. glue.py suppory mnli_m
3. all the tasks support multiple metrics, validation of supported metrics and the code about visualdl and log move to BasicTask, user can free to implement their metrics without considering log and visualdl.

2019-08-19 03:22 UTC, Steffy-zxf commented on paddlehub/finetune/task.py
> +            log_scores += "%s=%.3f " % (metric, scores[metric])
建议统一为保留5为小数

2019-08-19 03:22 UTC, Steffy-zxf commented on paddlehub/finetune/task.py
> +            log_scores += "%s=%.3f " % (metric, eval_scores[metric])
建议保留5位小数

2019-08-19 06:28 UTC, kinghuin commented on paddlehub/finetune/task.py
> +            log_scores += "%s=%.3f " % (metric, scores[metric])
已修改

2019-08-19 06:28 UTC, kinghuin commented on paddlehub/finetune/task.py
> +            log_scores += "%s=%.3f " % (metric, eval_scores[metric])
已修改

2019-08-20 07:06 UTC, nepeplwu requested changes

2019-08-20 07:06 UTC, nepeplwu commented on paddlehub/finetune/task.py
> +            if not self.hasloaded:
是否需要在下面的逻辑中将hasloaded置为True？另外还需要考虑多次交叉调用predict和finetune的情况

2019-08-20 07:06 UTC, nepeplwu commented on paddlehub/finetune/task.py
> +        self.hasloaded = False
建议修改为更直观的名字

2019-08-20 07:06 UTC, nepeplwu commented on paddlehub/finetune/task.py
> +            main_metric, main_value = list(eval_scores.items())[0]
使用scores.items[0]作为best_score的对比指标，会导致用户无法干预这个过程，建议选择metrics_choice[0]的第一个key作为对比指标

2019-08-20 07:06 UTC, nepeplwu commented on paddlehub/finetune/task.py
> +        scores = {}
阅读理解Task在没有合适的度量指标的情况下，是否重载_eval_end_event事件，通过loss来保存最优模型？

2019-08-21 06:54 UTC, kinghuin commented on paddlehub/finetune/task.py
> +            if not self.hasloaded:
已修改 并支持交叉调用

2019-08-21 06:54 UTC, kinghuin commented on paddlehub/finetune/task.py
> +        self.hasloaded = False
已修改 与is_checkpoint_loaded 相似名

2019-08-21 06:55 UTC, kinghuin commented on paddlehub/finetune/task.py
> +            main_metric, main_value = list(eval_scores.items())[0]
已修改

2019-08-21 06:55 UTC, kinghuin commented on paddlehub/finetune/task.py
> +        scores = {}
已重载

2019-08-22 11:20 UTC, nepeplwu approved these changes

2019-08-22 11:21 UTC, merged