Add dataset, module task, and demo of text-matching
PaddlePaddle/PaddleFormers pull request #1281
Opened 2021-03-04 13:30 UTC by KPatr1ck

2021-03-05 02:06 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +        elif task == 'text-matching':
组网实现不是Sentence-Transformer

参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/sentence_transformers

2021-03-05 02:27 UTC, Steffy-zxf requested changes
还缺少文本匹配demo 脚本运行示例

2021-03-05 02:27 UTC, Steffy-zxf commented on paddlehub/datasets/base_nlp_dataset.py
> +                if Version(paddlenlp.__version__) <= Version('2.0.0rc2'):
无须兼容PaddleNLP 2.0.0rc2 以下版本，匹配任务可以直接考虑paddlenlp 2.0.0rc6以上版本

2021-03-05 02:27 UTC, Steffy-zxf commented on paddlehub/datasets/base_nlp_dataset.py
> +            if Version(paddlenlp.__version__) >= Version('2.0.0rc5'):
无须兼容PaddleNLP 2.0.0rc2 以下版本，匹配任务可以直接考虑paddlenlp 2.0.0rc6以上版本

2021-03-05 02:27 UTC, Steffy-zxf commented on paddlehub/module/nlp_module.py
> +    def _convert_text_to_input(self, tokenizer, texts: List[str], max_seq_len: int, split_char: str):
建议不要轻易变动接口参数名

2021-03-05 02:27 UTC, Steffy-zxf commented on paddlehub/module/nlp_module.py
> +                encoded_inputs.append(tokenizer.encode(
无须兼容PaddleNLP 2.0.0rc2 以下版本，可以直接考虑paddlenlp 2.0.0rc6以上版本

2021-03-05 02:27 UTC, Steffy-zxf commented on paddlehub/module/nlp_module.py
> +                if Version(paddlenlp.__version__) <= Version('2.0.0rc2'):
无须兼容PaddleNLP 2.0.0rc2 以下版本，可以直接考虑paddlenlp 2.0.0rc6以上版本

2021-03-05 02:34 UTC, Steffy-zxf requested changes

2021-03-05 02:34 UTC, Steffy-zxf commented on modules/text/language_model/ernie_tiny/module.py
> +    def forward(self, input_ids, token_type_ids=None, input_ids2=None, token_type_ids2=None, position_ids=None, attention_mask=None, seq_lengths=None, labels=None):
建议保留原有`input_ids`, `token_type_ids`, `position_ids`, `attention_mask`, `seq_lengths`, `labels` 的参数，增加
`query_input_ids`, `query_token_type_ids`, `query_position_ids`, `query_attention_mask`, `query_seq_lengths`, 
`title_input_ids`, `title_token_type_ids`, `title_position_ids`, `title_attention_mask`, `title_seq_lengths` 
参数

2021-03-05 11:21 UTC, KPatr1ck commented on modules/text/language_model/ernie_tiny/module.py
> +        elif task == 'text-matching':
之前用的Sentence-Transformer中的CLS-token的方式，现已改为Mean Pooling，同步paddlenlp

2021-03-05 11:21 UTC, KPatr1ck commented on paddlehub/datasets/base_nlp_dataset.py
> +                if Version(paddlenlp.__version__) <= Version('2.0.0rc2'):
已改

2021-03-05 11:21 UTC, KPatr1ck commented on paddlehub/datasets/base_nlp_dataset.py
> +            if Version(paddlenlp.__version__) >= Version('2.0.0rc5'):
已改

2021-03-05 11:21 UTC, KPatr1ck commented on paddlehub/module/nlp_module.py
> +                encoded_inputs.append(tokenizer.encode(
已改

2021-03-05 11:21 UTC, KPatr1ck commented on paddlehub/module/nlp_module.py
> +                if Version(paddlenlp.__version__) <= Version('2.0.0rc2'):
已改

2021-03-05 11:22 UTC, KPatr1ck commented on modules/text/language_model/ernie_tiny/module.py
> +    def forward(self, input_ids, token_type_ids=None, input_ids2=None, token_type_ids2=None, position_ids=None, attention_mask=None, seq_lengths=None, labels=None):
已按review意见增加参数，原参数保持不变

2021-03-05 11:24 UTC, KPatr1ck commented on paddlehub/module/nlp_module.py
> +    def _convert_text_to_input(self, tokenizer, texts: List[str], max_seq_len: int, split_char: str):
因为text是一个列表，可能存在2个文本，为了方便理解而改动的
考虑到是内部使用的函数，所以将参数名从text改成了texts

2021-03-09 01:47 UTC, Steffy-zxf commented on demo/text_matching/predict.py
> +    label_map = {0: 'unmatch', 1: 'match'}
`{0: 'unmatched', 1: 'matched'}`

or

`{0: 'similar', 1: 'dissimilar'}`

2021-03-09 01:47 UTC, Steffy-zxf commented on paddlehub/datasets/lcqmc.py
> +#coding:utf-8
可去掉（paddlehub 要求py3）

2021-03-09 01:47 UTC, Steffy-zxf commented on demo/text_matching/predict.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
2021

2021-03-09 01:47 UTC, Steffy-zxf commented on demo/text_matching/train.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
2021

2021-03-09 03:04 UTC, KPatr1ck commented on demo/text_matching/predict.py
> +    label_map = {0: 'unmatch', 1: 'match'}
已改为'similar'和'dissimilar'

2021-03-09 03:04 UTC, KPatr1ck commented on demo/text_matching/predict.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
已更正

2021-03-09 03:04 UTC, KPatr1ck commented on demo/text_matching/train.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
已更正

2021-03-09 03:05 UTC, KPatr1ck commented on paddlehub/datasets/lcqmc.py
> +#coding:utf-8
已删除

2021-03-11 01:55 UTC, Steffy-zxf approved these changes
LGTM

2021-03-11 01:57 UTC, merged