Correcting the error in example of Chinese segmentation in README_ch.md
PaddlePaddle/PaddleFormers pull request #1585
Opened 2021-08-23 06:51 UTC by Wgm-Inspur

在原先的“极简中文分词案例”中，存在下述问题：
A、最后两句不属于案例本身，放在一起执行，启动LAC（词法分析）服务后程序不停止。
B、在最后1句中，“hub”前面的“！”有问题，应该修改为“!”。
C、倒数第2行注释“启动serving服务”不准确，应该是“启动lac（词法分析）服务”。
D、在倒数第2行注释中，“更多模型搜索可参考***”和前面注释不搭配。
针对上述问题，对这部分代码进行调整，经测试可以正常运行。

2021-08-23 06:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleHub?pullRequest=1585) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleHub?pullRequest=1585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleHub?pullRequest=1585) it.</sub>

2021-08-23 08:58 UTC, KPatr1ck requested changes
你好，感谢你的反馈和pr提交。

关于README.md中的描述修改提了两点小建议，具体参考review意见。
此外，建议把下面2行命令行中执行的安装语句也剥离出来，可以修改完成后在此pr一并提交 ～
```shell
!pip install --upgrade paddlepaddle -i https://mirror.baidu.com/pypi/simple
!pip install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple
```

2021-08-23 08:58 UTC, KPatr1ck commented on README_ch.md
> +### 一行代码启动lac（词法分析）服务，
建议可以改为：“一行代码部署lac（词法分析）模型”

2021-08-23 08:58 UTC, KPatr1ck commented on README_ch.md
> + 更多模型介绍可以参考[模型搜索](https://www.paddlepaddle.org.cn/hublist)
建议改为：“欢迎用户通过[模型搜索](https://www.paddlepaddle.org.cn/hublist)发现更多实用的预训练模型！”

2021-08-23 09:40 UTC, Wgm-Inspur commented
已经按照建议修改README_ch.md，路径如下：
[README_ch.md](https://github.com/PaddlePaddle/PaddleHub/files/7030850/README_ch.md)

2021-08-24 03:18 UTC, Wgm-Inspur commented
根据“README_ch.md”调整后的内容，修改和完善“README.md”，包括：
1、添加使用一行代码部署HubServing服务的示例。
2、为中文分词示例添加标题注释。
3、单独提取中文分词示例中安装Paddle组件的语句。
4、添加“Models List”的说明。

2021-08-25 10:22 UTC, Wgm-Inspur commented
Please merge my contribution.

2021-08-26 03:11 UTC, Wgm-Inspur commented on README_ch.md
> +### 一行代码启动lac（词法分析）服务，
已经修改并提交了。

2021-08-26 03:11 UTC, Wgm-Inspur commented on README_ch.md
> + 更多模型介绍可以参考[模型搜索](https://www.paddlepaddle.org.cn/hublist)
已经修改并提交了。

2021-08-26 03:13 UTC, Wgm-Inspur commented
> 你好，感谢你的反馈和pr提交。
> 
> 关于README.md中的描述修改提了两点小建议，具体参考review意见。
> 此外，建议把下面2行命令行中执行的安装语句也剥离出来，可以修改完成后在此pr一并提交 ～
> 
> ```shell
> !pip install --upgrade paddlepaddle -i https://mirror.baidu.com/pypi/simple
> !pip install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple
> ```

已经修改并提交了。

2021-08-26 03:35 UTC, KPatr1ck commented
> > 你好，感谢你的反馈和pr提交。
> > 关于README.md中的描述修改提了两点小建议，具体参考review意见。
> > 此外，建议把下面2行命令行中执行的安装语句也剥离出来，可以修改完成后在此pr一并提交 ～
> > ```shell
> > !pip install --upgrade paddlepaddle -i https://mirror.baidu.com/pypi/simple
> > !pip install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple
> > ```
> 
> 已经修改并提交了。

好的，我检查一下，没问题的话就merge。

2021-08-26 04:00 UTC, merged

2021-08-26 04:00 UTC, KPatr1ck approved these changes