Fix docs
PaddlePaddle/PaddleFormers pull request #296
Opened 2020-01-01 07:29 UTC by Steffy-zxf

update README.md

2020-01-01 08:56 UTC, ZeyuChen requested changes
去掉用成语来说举一反三这句话吧。

2020-01-01 08:56 UTC, ZeyuChen commented on README.md
> +迁移学习(Transfer Learning)通俗来讲，就是运用已有的知识来学习新的知识，核心是找到已有知识和新知识之间的相似性，用成语来说就是举一反三。PaddleHub提供了Fine-tune API，只需要少量代码即可完成深度学习模型在自然语言处理和计算机视觉场景下的迁移学习。
“用成语来说”这种句式对于工程师感觉太显得太初级。

2020-01-02 01:49 UTC, Steffy-zxf commented on README.md
> +迁移学习(Transfer Learning)通俗来讲，就是运用已有的知识来学习新的知识，核心是找到已有知识和新知识之间的相似性，用成语来说就是举一反三。PaddleHub提供了Fine-tune API，只需要少量代码即可完成深度学习模型在自然语言处理和计算机视觉场景下的迁移学习。
Done

2020-01-02 03:44 UTC, ZeyuChen approved these changes
LGTM

2020-01-02 03:45 UTC, merged