update version
PaddlePaddle/PaddleFormers pull request #594
Opened 2020-05-13 09:59 UTC by Steffy-zxf

1. simply requirements
2. update version
3. update ssd demo

2020-05-14 16:54 UTC, ZeyuChen requested changes
几个小地方需要修改，其他没问题。

2020-05-14 16:54 UTC, ZeyuChen commented on demo/text_classification/README.md
> +**PaddleHub 1.7.0以上版本支持在Transformer类预训练模型之后拼接预置网络(bow, bilstm, cnn, dpcnn, gru, lstm)完成文本分类任务**
bow->BOW
bilstm->Bi-LSTM
模型结构需要用大写

2020-05-14 16:54 UTC, ZeyuChen commented on requirements.txt
>  opencv-python
opencv可删除，paddle自带

2020-05-14 16:54 UTC, ZeyuChen commented on requirements.txt
>  opencv-python
opencv-python可删除，paddle框架自带

2020-05-15 02:50 UTC, Steffy-zxf commented on demo/text_classification/README.md
> +**PaddleHub 1.7.0以上版本支持在Transformer类预训练模型之后拼接预置网络(bow, bilstm, cnn, dpcnn, gru, lstm)完成文本分类任务**
已修改

2020-05-15 02:51 UTC, Steffy-zxf commented on requirements.txt
>  opencv-python
对比了paddle框架requirements里面没有opencv，暂不修改

2020-05-15 02:51 UTC, Steffy-zxf commented on requirements.txt
>  opencv-python
对比了paddle框架requirements里面没有opencv，暂不修改

2020-05-17 04:07 UTC, merged