【DO NOT MERGE】Tokenizer解耦
PaddlePaddle/PaddleFormers pull request #643
Opened 2020-05-28 09:22 UTC by kinghuin

tokenizer解耦，已跑通BQ数据集文本分类
【DO NOT MERGE】这个PR的代码需要合入到develop中，但develop现在还没merge release/v1.7，diff会比较大，不便review

2020-05-28 13:52 UTC, ZeyuChen requested changes
Few english description need to modify.
eg. XXXX is deprecate after paddlehub 1.x

2020-05-28 13:52 UTC, ZeyuChen commented on paddlehub/finetune/task/base_task.py
> +        feed_list (list): the inputs name. Deprecated in hub 1.8.
It will be deprecated since paddlehub v1.8. Use full package name padddlehub instead of hub in comments

2020-05-28 13:52 UTC, ZeyuChen commented on paddlehub/finetune/task/base_task.py
> +        feed_list (list): the inputs name. Deprecated in hub 1.8.
It will be deprecated after paddlehub v1.8. Use full package name padddlehub instead of hub in comments

2020-05-28 13:52 UTC, ZeyuChen commented on paddlehub/finetune/task/base_task.py
> +                         or a plaintext string list when the task is initialized with data_reader param (deprecated in hub 1.8).
(deprecated after paddlehub 1.8)

2020-05-29 02:42 UTC, kinghuin commented on paddlehub/finetune/task/base_task.py
> +        feed_list (list): the inputs name. Deprecated in hub 1.8.
修改为了"Deprecated in paddlehub v1.8"，因为v1.8发布时，这里不是“将废弃”，而是已经废弃了。

2020-05-29 02:42 UTC, kinghuin commented on paddlehub/finetune/task/base_task.py
> +                         or a plaintext string list when the task is initialized with data_reader param (deprecated in hub 1.8).
修改为了deprecated in paddlehub v1.8，看了下python标准库里面他们用的"in"，这里也用了"in"

2020-06-02 02:03 UTC, closed without merging