Tokenizer reconsitution
PaddlePaddle/PaddleFormers pull request #677
Opened 2020-06-08 11:37 UTC by kinghuin

1. 新增BertTokenizer和ErnieTinyTokenizer
2. 新增TextClassificationDataset, RegressionDataset, SequenceLabelDataset, MultiLabelDataset, MRCDataset(支持进度条)。dataset支持接收tokenizer，直接对examples进行预处理。
3. task支持接收dataset，取消掉了feed_list参数。ReadingComprehensionTask后处理支持进度条。
4. 修改了各个demo以适配新写法，dataset中新增batch_records_generator用于动态图组batch且减少PAD数量。已验证动态图和各个任务新老demo都能跑通。
5. 修复loss=acc的bug

2020-06-09 08:01 UTC, nepeplwu commented on paddlehub/finetune/task/base_task.py
> +                "PaddleHub v1.8 has deprecated the reader and feed_list parameters in Task. We provided an easier usage, "
图像分类不应该提示这句话

2020-06-09 08:01 UTC, nepeplwu commented on paddlehub/dataset/base_nlp_dataset.py
> +from tqdm import tqdm
requirements.txt要加上

2020-06-09 08:24 UTC, kinghuin commented on paddlehub/finetune/task/base_task.py
> +                "PaddleHub v1.8 has deprecated the reader and feed_list parameters in Task. We provided an easier usage, "
已优化

2020-06-09 08:24 UTC, kinghuin commented on paddlehub/dataset/base_nlp_dataset.py
> +from tqdm import tqdm
已添加

2020-06-10 17:25 UTC, ZeyuChen requested changes
Formalize class name, and remove Chinese comments.

2020-06-10 17:25 UTC, ZeyuChen commented on demo/sequence_labeling/predict.py
>      # If using python 2, prefix "u" is necessary
remove this comments for python2

2020-06-10 17:25 UTC, ZeyuChen commented on demo/sequence_labeling/sequence_label_dygraph.py
> +            for batch_id, data in enumerate(
Why use Chinese comments here?

2020-06-10 17:25 UTC, ZeyuChen commented on demo/sequence_labeling/sequence_label_dygraph.py
> +            num_classes=dataset.num_labels, transformer=module)
Rename `TransformerSequenceLabelLayer` to `TransformerSeqLabeling`
Don't name a Class name end with "Layer" in dygraph mode.

2020-06-10 17:25 UTC, ZeyuChen commented on paddlehub/dataset/bq.py
> +class BQ(TextClassificationDataset):
No any comments for BQ dataset?

2020-06-10 17:25 UTC, ZeyuChen commented on paddlehub/dataset/msra_ner.py
> +class MSRA_NER(SequenceLabelDataset):
Since SequenceLabel is a verb, it would be better use a noun. 
If we say XXXDataset, then XXX should be a noun instead of verb.
So `SeqLabelingDataset` would be a better class name.

2020-06-11 02:56 UTC, kinghuin commented on demo/sequence_labeling/predict.py
>      # If using python 2, prefix "u" is necessary
DONE

2020-06-11 02:56 UTC, kinghuin commented on demo/sequence_labeling/sequence_label_dygraph.py
> +            num_classes=dataset.num_labels, transformer=module)
DONE

2020-06-11 02:56 UTC, kinghuin commented on demo/sequence_labeling/sequence_label_dygraph.py
> +            for batch_id, data in enumerate(
Deleted

2020-06-11 02:56 UTC, kinghuin commented on paddlehub/dataset/bq.py
> +class BQ(TextClassificationDataset):
Added

2020-06-11 03:25 UTC, Steffy-zxf commented on paddlehub/dataset/base_nlp_dataset.py
> +        """
发现 TextClassificationDataset、RegressionDataset等 _convert_examples_to_records方法 和 BaseNLPDataset的_convert_examples_to_records方法 是一样的，为什么还要在子类里面重写？

2020-06-11 03:35 UTC, kinghuin commented on paddlehub/dataset/base_nlp_dataset.py
> +        """
不一样，label的处理上

2020-06-11 03:45 UTC, Steffy-zxf commented on paddlehub/dataset/base_nlp_dataset.py
> +        """
我看 TextClassificationDataset _convert_examples_to_records方法和BaseNLPDataset的_convert_examples_to_records方法 是完全一样的。

2020-06-11 03:55 UTC, kinghuin commented on paddlehub/dataset/base_nlp_dataset.py
> +        """
不一样啊，BaseNLPDataset的_convert_examples_to_records兼容了分类和回归。

2020-06-11 03:57 UTC, kinghuin commented on paddlehub/dataset/base_nlp_dataset.py
> +        """
classification
record["label"] = self.label_list.index(example.label)
regression
record["label"] = float(example.label)
basenlp
record["label"] = self.label_list.index(example.label) if self.label_list else float(example.label)

2020-06-12 09:33 UTC, Steffy-zxf commented on paddlehub/tokenizer/bert_tokenizer.py
> +        out_string = " ".join(tokens).replace(" ##", "").strip()
这里似乎没有考虑中文的处理，tokens以空格切分是英文的习惯。中文的话，是不是不需要再以空格分割？同理，decode是不是需要考虑下中英文的区别呢

2020-06-16 06:20 UTC, kinghuin commented on paddlehub/tokenizer/bert_tokenizer.py
> +        out_string = " ".join(tokens).replace(" ##", "").strip()
是的，没有考虑到。中英文混排是个问题，我先记一下

2020-06-17 04:09 UTC, kinghuin commented on paddlehub/dataset/msra_ner.py
> +class MSRA_NER(SequenceLabelDataset):
Modified

2020-06-18 10:52 UTC, merged