Add topic model
PaddlePaddle/PaddleFormers pull request #750
Opened 2020-07-15 02:39 UTC by DesmonDay

Add 7 topic model modules, including lda_news, lda_novel, lda_webpage, slda_news, slda_novel, slda_webpage, slda_weibo.

2020-07-15 08:41 UTC, Steffy-zxf requested changes

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/README.md
> +paddlehub >= 1.8.0
paddlehub >= 1.7.0

是否 还有其他依赖？比如numpy

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/README.md
> +本Module基于的数据集为百度自建的新闻领域数据集。主题模型(Topic Model)是以无监督学习的方式对文档的隐含语义结构进行聚类的统计模型，其中LDA(Latent Dirichlet Allocation)算法是主题模型的一种。LDA根据对词的共现信息的分析，拟合出词-文档-主题的分布，从而将词、文本映射到一个语义空间中。
本Module基于的数据集为百度自建的新闻领域数据集。这句话可以挪到最后

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/model.py
> +from tqdm import tqdm
numpy 和 tqdm 都属于第三方依赖，代码不符合pep8规范

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/module.py
> +import numpy as np
同上

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/module.py
> +    author="baidu",
author 可以写你的github id

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/sampler.py
> +from tqdm import tqdm
同上

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/semantic_matching.py
> +import numpy as np
同上

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_novel/README.md
> +本Module基于的数据集为百度自建的小说领域数据集。主题模型(Topic Model)是以无监督学习的方式对文档的隐含语义结构进行聚类的统计模型，其中LDA(Latent Dirichlet Allocation)算法是主题模型的一种。LDA根据对词的共现信息的分析，拟合出词-文档-主题的分布，从而将词、文本映射到一个语义空间中。
本Module基于的数据集为百度自建的小说领域数据集。可以放在末尾。

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_novel/README.md
> +paddlehub >= 1.8.0
paddlehub >= 1.7.0

第三方依赖？

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_news/module.py
> +        """
需要在预测接口加上 第三方依赖的检查，运行环境是否已经安装了依赖。如果安装了，则继续运行，否则终止程序。

其他预测接口同理

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_novel/module.py
> +    author="baidu",
同上

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/lda_novel/module.py
> +    def cal_doc_keywords_similarity(self, document, top_k=10):
依赖检查，同上

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/slda_news/module.py
> +    author="baidu",
同上

2020-07-15 08:41 UTC, Steffy-zxf commented on hub_module/modules/text/semantic_model/slda_news/module.py
> +        """
依赖检查，同上

2020-07-15 09:32 UTC, Steffy-zxf commented
还需要补充各个module的单测脚本

2020-07-15 10:08 UTC, DesmonDay commented
和random seed相关的结果，怎么测试呢？

---Original---
From: "Steffy-zxf"<notifications@github.com&gt;
Date: Wed, Jul 15, 2020 17:33 PM
To: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
Cc: "SiMing Dai"<908660116@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
Subject: Re: [PaddlePaddle/PaddleHub] Add topic model (#750)




 
还需要补充各个module的单测脚本
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-07-16 04:01 UTC, kinghuin commented
个人感觉readme依赖中numpy tqdm这些可以不写，因为paddlehub的安装中已经安装了这些小依赖

2020-07-16 04:05 UTC, Steffy-zxf commented
> 个人感觉readme依赖中numpy tqdm这些可以不写，因为paddlehub的安装中已经安装了这些小依赖，否则很多项目的依赖项都显得很冗余

那是1.8之后增加的依赖，topic model不用等1.8版本

2020-07-16 04:06 UTC, DesmonDay commented
1.7版本没有tqdm，不过numpy的我会去掉的。



---Original---
From: "kinghuin"<notifications@github.com&gt;
Date: Thu, Jul 16, 2020 12:02 PM
To: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
Cc: "SiMing Dai"<908660116@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
Subject: Re: [PaddlePaddle/PaddleHub] Add topic model (#750)




 
个人感觉readme依赖中numpy tqdm这些可以不写，因为paddlehub的安装中已经安装了这些小依赖
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-07-17 05:25 UTC, closed without merging