add new documents
PaddlePaddle/PaddleFormers pull request #774
Opened 2020-07-24 02:54 UTC by Leowolfking

123

2020-07-24 02:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleHub?pullRequest=774) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleHub?pullRequest=774) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleHub?pullRequest=774) it.</sub>

2020-07-27 04:02 UTC, Steffy-zxf requested changes

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +[<paddlehub.finetune.task.base_task.RunState at 0x7f7b3972ef50>,
这些`[<paddlehub.finetune.task.base_task.RunState at 0x7f7b3972ef50>,` 输出可以去掉

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/cmd_quick_run.md
> +!pip install paddlehub==1.6.1 -i https://pypi.tuna.tsinghua.edu.cn/simple #指定版本安装PaddleHub，使用清华源更稳定、更迅速
`!` 是在jupyter shell上输入命令行，需要的。在终端上输入不需要，可以加上 `$` 表示 这是命令

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/cmd_quick_run.md
> +可点击[Github的网址](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7)了解详情。
wiki文档会被废弃，不要再往wiki文档上引导

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/cmd_quick_run.md
> +# 展示预测结果
如何展示预测结果，个人感觉不是很有必要在文档上给用户说明。这里写的是使用matplotlib进行展示，是在jupyter上可视化的用法。其实如果用户在本机上执行的话，这种不是最好最直接的方式。

个人建议可以说明下，visualization 和 output_dir的作用，如果用户想要看预测结果图片，可以去哪里找。

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/cmd_quick_run.md
> +    --2020-07-22 12:19:52--  https://paddlehub.bj.bcebos.com/resources/test_image.jpg
同理这里相应的输出，个人觉得不是很有必要

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/cmd_quick_run.md
> +![png](./imgs/output_14_0.png)
pr没有添加上这张图片

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/cmd_quick_run.md
> +* download：用于下载百度提供的Module；
用于下载百度飞桨PaddleHub提供的Module；

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/cmd_quick_run.md
> +>值得注意的是，不是所有的Module都支持通过命令行预测 (例如BERT/ERNIE Transformer类模型，一般需要搭配任务进行finetune)， 也不是所有的Module都可用于finetune（例如LAC词法分析模型，我们不建议用户用于finetune）。建议提前阅读预训练模型的介绍文档了解使用场景。
1. 正式文档上，建议不要使用第一人称，可以换成

如不建议用户使用词法分析LAC模型 Fine-tune。

2. 建议提前阅读预训练模型的介绍文档了解使用场景。

这里可以给出 预训练模型文档联建，https://www.paddlepaddle.org.cn/hublist

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +* 用户已安装PaddleHub。
这里可以给一个 PaddleHub 如何安装的跳转链接

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +* 准备好用于迁移学习的数据，用户可以选择使用PaddleHub提供的数据集或者自定义数据集，如果是自定义数据，需要参考“自定义数据集如何Fine-tune”对数据集处理。
自定义数据集如何Fine-tune

也可以给一个跳转链接

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +使用如下代码加载预训练模型，本例使用ERNIE预训练模型来完成文本分类任务。ERNIE（Enhanced Representation through kNowledge IntEgration）是百度提出的语义表示模型，以Transformer Encoder为网络基本组件，其预训练过程利用了更丰富的语义知识和更多的语义任务，用户可以使用该预训练模型随时逐步引入不同的自定义任务，例如命名实体预
ERNIE 那块可以给一个ernie module文档跳转链接

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +    [32m[2020-07-23 11:26:48,358] [    INFO] - Installing ernie module[0m
这里可以向左对齐，前后的`[32m` 和 `[0m` 是编辑器粘贴的原因，可以去掉

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +##### **加载PaddleHub自带数据集**
PaddleHub内置数据集

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +    Downloading chnsenticorp.tar.gz
向左对齐

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +|DefaultFinetuneStrategy|默认的优化策略。其对应参数如下：<br>* learning_rate: 全局学习率。默认为1e-4。<br>* optimizer_name: 优化器名称。默认adam。<br>* regularization_coeff: 正则化的λ参数。默认为1e-3。<br>在图像分类任务中推荐使用此优化策略。|strategy = hub.Defaul
![image](https://user-images.githubusercontent.com/48793257/88501563-6ddc0500-cffe-11ea-847f-c27f922687d6.png)

缩进，4个空格

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +    [32m[2020-07-23 11:27:15,518] [    INFO] - Checkpoint dir: ckpt_20200723112715[0m
同上

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/how_to_finetune.md
> +run_states = cls_task.predict(data=data)
这里应该是老版本的用法了，`cls_task.predict(data=data, return_results=False)`

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/more_demos.md
> +# PaddleHub更多体验Demos
demo 不止以下这些，更全的demo：可以参考 https://aistudio.baidu.com/aistudio/projectdetail/231146

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/python_use_hub.md
> +# 通过Python代码调用方式 使用PaddleHub
为什么中间需要加空格呢

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/python_use_hub.md
> +!hub install lac==2.1.1
这里不需要指定让用户安装某个版本的module。因为module 会升级，我们希望用户使用最新版本的module

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/python_use_hub.md
> +!pip install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple #升级到最新版本，使用清华源更稳定、更迅速
既然两条命令都是安装paddlehub，那么第一个指定版本的安装命令可以把注释提到最前面

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/python_use_hub.md
> +![png](output_4_1.png)
图片统一放在 docs/imgs文件夹下

2020-07-27 04:02 UTC, Steffy-zxf commented on docs/tutorial/how_to_finetune.md
> +## **迁移学习**
这个文档重复了，在docs/ 和 docs/tutorial/下都有这个文档

2020-07-28 09:31 UTC, moguguo commented on docs/cmd_quick_run.md
> +!pip install paddlehub==1.6.1 -i https://pypi.tuna.tsinghua.edu.cn/simple #指定版本安装PaddleHub，使用清华源更稳定、更迅速
接纳，后续文档统一命令行样式为：命令前加“$+空格”，如“$ pip install paddlehub”

2020-07-28 09:33 UTC, moguguo commented on docs/cmd_quick_run.md
> +可点击[Github的网址](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7)了解详情。
接纳，这个地方要做一下到文档内命令行参考章节的引用，文档写好以后要替换一下链接。

2020-07-28 09:50 UTC, moguguo commented on docs/cmd_quick_run.md
> +# 展示预测结果
接纳，只在AI Studio保留可视化相关代码，github文档中统一去掉。

2020-07-28 09:56 UTC, moguguo commented on docs/cmd_quick_run.md
> +    --2020-07-22 12:19:52--  https://paddlehub.bj.bcebos.com/resources/test_image.jpg
接纳

2020-07-28 09:57 UTC, moguguo commented on docs/cmd_quick_run.md
> +![png](./imgs/output_14_0.png)
图片如何提交，待统一确认提交规则。

2020-07-28 09:57 UTC, moguguo commented on docs/cmd_quick_run.md
> +* download：用于下载百度提供的Module；
接纳

2020-07-28 10:05 UTC, moguguo commented on docs/cmd_quick_run.md
> +>值得注意的是，不是所有的Module都支持通过命令行预测 (例如BERT/ERNIE Transformer类模型，一般需要搭配任务进行finetune)， 也不是所有的Module都可用于finetune（例如LAC词法分析模型，我们不建议用户用于finetune）。建议提前阅读预训练模型的介绍文档了解使用场景。
接纳，1.修改说法，2.补充链接

2020-07-28 10:07 UTC, moguguo commented on docs/more_demos.md
> +# PaddleHub更多体验Demos
待确认，这里需要统一一下，我们后续只保留一个全demo的链接，看保留哪一个？

2020-07-28 10:08 UTC, moguguo commented on docs/python_use_hub.md
> +# 通过Python代码调用方式 使用PaddleHub
接纳，去掉

2020-07-28 10:12 UTC, moguguo commented on docs/python_use_hub.md
> +!hub install lac==2.1.1
接纳，默认去掉版本号，仅说明可以有指定版本的方法。

2020-07-28 10:14 UTC, moguguo commented on docs/python_use_hub.md
> +!pip install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple #升级到最新版本，使用清华源更稳定、更迅速
接纳，只留两条注释，并放到命令前面
#指定版本安装PaddleHub，使用清华源更稳定、更迅速
#升级到最新版本，使用清华源更稳定、更迅速

2020-07-28 10:14 UTC, moguguo commented on docs/python_use_hub.md
> +![png](output_4_1.png)
待确认，有图片大小限制，待统一规则后上传

2020-07-28 10:16 UTC, Leowolfking commented on docs/how_to_finetune.md
> +[<paddlehub.finetune.task.base_task.RunState at 0x7f7b3972ef50>,
接受，已删除这部分显示信息，只保留评价值的部分。

2020-07-28 10:24 UTC, moguguo commented on docs/more_demos.md
> +# PaddleHub更多体验Demos
已和PM确认，后续官方demo统一链到这个链接：https://aistudio.baidu.com/aistudio/personalcenter/thirdview/79927

2020-07-30 08:30 UTC, Steffy-zxf approved these changes
LGTM

2020-07-30 08:31 UTC, merged